config/routes.rb
Rails.application.routes.draw do
  
  resources :project_statuses
  resources :contacts
  resources :companies
  resources :task_statuses
  resources :task_logs
  resources :tasks
  resources :workers
  resources :components
  resources :projects
  root 'static_pages#home'
  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :contacts
    has_many :projects

    validates :name, presence: true
end

app/models/component.rb
class Component < ApplicationRecord
    has_many :workers
    has_many :users, through: :workers
    has_many :tasks
    belongs_to :project

    validates :name, presence: true, length: { minimum: 6 }
    validates :project, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :company

    validates :surname, presence: true
    validates :name,  presence: true
    validates :company, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    belongs_to :company
    belongs_to :project_status
    has_many :components

    validates :user, presence: true
    validates :name,  presence: true
    validates :company, presence: true
    validates :project_status, presence: true
end

app/models/project_status.rb
class ProjectStatus < ApplicationRecord
    has_many :projects

    validates :name,  presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :component
    belongs_to :task_status
    has_many :task_logs

    validates :name, presence: true
    validates :component, presence: true
    validates :task_status, presence: true
end

app/models/task_log.rb
class TaskLog < ApplicationRecord
    belongs_to :task
    belongs_to :user

    validates :task, presence: true
    validates :user, presence: true
    validates :title, presence: true, length: { minimum: 6 }
end

app/models/task_status.rb
class TaskStatus < ApplicationRecord
    has_many :tasks

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :workers, dependent: :destroy
  has_many :components, through: :workers
  has_many :projects
  has_many :task_logs

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_secure_password
  
  before_save { self.email = email.downcase }
  
  validates :password, presence: true, length: { minimum: 6 }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
                    
                    
  attr_accessor :remember_token
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  
end

app/models/worker.rb
class Worker < ApplicationRecord
    belongs_to :user
    belongs_to :component

    validates :user, presence: true 
    validates :component, presence: true
end

app/controllers/task_logs_controller.rb
class TaskLogsController < ApplicationController
  before_action :set_task_log, only: [:show, :edit, :update, :destroy]
  before_action :admin_user,     only: [:index, :edit, :update, :destroy]
  
  def admin_user
    redirect_to(root_url) unless current_user != nil && current_user.admin?
  end
  # GET /task_logs
  # GET /task_logs.json
  def index
    @task_logs = TaskLog.all
  end

  # GET /task_logs/1
  # GET /task_logs/1.json
  def show
  end

  # GET /task_logs/new
  def new
    @task_log = TaskLog.new
  end

  # GET /task_logs/1/edit
  def edit
  end

  # POST /task_logs
  # POST /task_logs.json
  def create
    @task_log = TaskLog.new(task_log_params)

    respond_to do |format|
      if @task_log.save
        flash[:success] = "Task log created"
        format.html { redirect_to @task_log, notice: 'Task log was successfully created.' }
        format.json { render :show, status: :created, location: @task_log }
      else
        format.html { render :new }
        format.json { render json: @task_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_logs/1
  # PATCH/PUT /task_logs/1.json
  def update
    respond_to do |format|
      if @task_log.update(task_log_params)
        flash[:success] = "Task log updated"
        format.html { redirect_to @task_log, notice: 'Task log was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_log }
      else
        format.html { render :edit }
        format.json { render json: @task_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_logs/1
  # DELETE /task_logs/1.json
  def destroy
    @task_log.destroy
    respond_to do |format|
      flash[:success] = "Task log deleted"
      format.html { redirect_to task_logs_url, notice: 'Task log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_log
      @task_log = TaskLog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_log_params
      params.require(:task_log).permit(:task_id, :user_id, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
   # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
   # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user?(user)
    user && user == current_user
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/task_logs_helper.rb
module TaskLogsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/task_logs/_form.html.erb
<%= form_with(model: task_log) do |form| %>
  <% if task_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_log.errors.count, "error") %> prohibited this task_log from being saved:</h2>

      <ul>
        <% task_log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.number_field :task_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_logs/_task_log.html.erb
<li>
    <ul>
        <li>Title: <%= task_log.title %></li>
        <li>Content: <%= task_log.content %></li>
        <li>Author: <%= task_log.user.name %></li>
        <li>Task: <%= task_log.task.name %></li>
        <% if current_user.admin?%>
            <li><%= link_to 'Show', task_log %>
            <%= link_to 'Edit', edit_task_log_path(task_log) %>
            <%= link_to 'Destroy', task_log, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </li>
    </ul>
</li>
<br>

app/views/task_logs/edit.html.erb
<h1>Editing Task Log</h1>

<%= render 'form', task_log: @task_log %>

<%= link_to 'Show', @task_log %> |
<%= link_to 'Back', task_logs_path %>

app/views/task_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Logs</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_logs.each do |task_log| %>
      <tr>
        <td><%= task_log.task_id %></td>
        <td><%= task_log.user_id %></td>
        <td><%= task_log.title %></td>
        <td><%= task_log.content %></td>
        <td><%= link_to 'Show', task_log %></td>
        <td><%= link_to 'Edit', edit_task_log_path(task_log) %></td>
        <td><%= link_to 'Destroy', task_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Log', new_task_log_path %>

app/views/task_logs/new.html.erb
<h1>New Task Log</h1>

<%= render 'form', task_log: @task_log %>

<%= link_to 'Back', task_logs_path %>

app/views/task_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @task_log.task_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @task_log.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task_log.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task_log.content %>
</p>

<%= link_to 'Edit', edit_task_log_path(@task_log) %> |
<%= link_to 'Back', task_logs_path %>