config/routes.rb
Rails.application.routes.draw do
  
  resources :project_statuses
  resources :contacts
  resources :companies
  resources :task_statuses
  resources :task_logs
  resources :tasks
  resources :workers
  resources :components
  resources :projects
  root 'static_pages#home'
  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :contacts
    has_many :projects

    validates :name, presence: true
end

app/models/component.rb
class Component < ApplicationRecord
    has_many :workers
    has_many :users, through: :workers
    has_many :tasks
    belongs_to :project

    validates :name, presence: true, length: { minimum: 6 }
    validates :project, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :company

    validates :surname, presence: true
    validates :name,  presence: true
    validates :company, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    belongs_to :company
    belongs_to :project_status
    has_many :components

    validates :user, presence: true
    validates :name,  presence: true
    validates :company, presence: true
    validates :project_status, presence: true
end

app/models/project_status.rb
class ProjectStatus < ApplicationRecord
    has_many :projects

    validates :name,  presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :component
    belongs_to :task_status
    has_many :task_logs

    validates :name, presence: true
    validates :component, presence: true
    validates :task_status, presence: true
end

app/models/task_log.rb
class TaskLog < ApplicationRecord
    belongs_to :task
    belongs_to :user

    validates :task, presence: true
    validates :user, presence: true
    validates :title, presence: true, length: { minimum: 6 }
end

app/models/task_status.rb
class TaskStatus < ApplicationRecord
    has_many :tasks

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :workers, dependent: :destroy
  has_many :components, through: :workers
  has_many :projects
  has_many :task_logs

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_secure_password
  
  before_save { self.email = email.downcase }
  
  validates :password, presence: true, length: { minimum: 6 }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
                    
                    
  attr_accessor :remember_token
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  
end

app/models/worker.rb
class Worker < ApplicationRecord
    belongs_to :user
    belongs_to :component

    validates :user, presence: true 
    validates :component, presence: true
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
   # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
   # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user?(user)
    user && user == current_user
  end
  
end

app/helpers/task_logs_helper.rb
module TaskLogsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Luka Petrovic RN33/18
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "temporio", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path  %></li>
          <li><%= link_to "Companies", companies_path  %></li>
          <% if current_user.admin? %>
              <li><%= link_to "Project statuses", project_statuses_path  %></li>
              <li><%= link_to "Task statuses", task_statuses_path  %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user)  %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>